<?php

/**
 * Admin_Add
 * Responsible for displaying and process the data entered into the
 * add interface for this table.
 *
 * @package     Database Project
 * @subpackage  controllers
 * @category    platform
 * @author      Crystal Barton
 * @version     1.00
 */
class Admin_Add extends MY_Controller
{

	var $table = 'platform';
	var $page = 'add';
	var $title = 'Platform >> Add Item';
	var $_item = array();

	
	/**
	 * Default Constructor.
	 */
	function __construct()
	{ 
		parent::__construct();
		$this->load->model( $this->table.'_model', 'table_model' );
	}


	/**
	 * Display the add interface for the platform.
	 */
	function index()
	{
		if( $this->input->post() )
		{
			// Process the post data.
			$this->_process_post();
			$this->_item = $this->input->post();
		}
		else
		{
			// Get the item's data.
			$this->_item = $this->table_model->get_platform_for_admin_add();
		}
		
		// Store the game and if there was an error.
		$this->add_content( 'item', $this->_item );
		$this->add_content( 'error', $this->post_processed_errored() );
		
		// Add stylesheets and javascript files.
		$this->add_style( 'util/jquery.image-selector' );
		$this->add_style( 'util/jquery.tag-selector' );
		$this->add_style( 'admin' );
		$this->add_script( 'util/jquery.image-selector' );
		$this->add_script( 'util/jquery.tag-selector' );
		$this->add_script( 'platform/admin' );
		
		// Show the add item interface.
		$this->show_page( $this->table.'/'.$this->page, $this->title, TRUE );
	}


	/**
	 * Attempts to add the new platform into the database.
	 */
	function _process_post()
	{
		// Start the database transaction.
		$this->start_transaction();
		
		// Check if the item already exists.
		$already_exists = $this->table_model->platform_exists(
			$this->input->post('name')
		);
		if( $this->has_error() ) return;
		
		// The platform already exists.
		if( $already_exists )
		{
			$this->set_results( FALSE, 'The Platform "'.$this->input->post('name') . '" already exists.' );
			return;
		}

		// Add the platform.
		$result = $this->table_model->add_platform(
			$this->input->post('name'),
		 	$this->input->post('maker'),
		 	$this->input->post('description'),
		 	$this->input->post('icon'),
			$this->input->post('thumbnail'),
			$this->input->post('artwork')
		);
		if( $this->has_error() ) return;
		
		// Get the platform id auto-generated by the platform table.
		$id = $this->table_model->get_platform_id(
			$this->input->post('name')
		);
		if( $this->has_error() ) return;
		$this->add_content( 'id', $id );
		
		// The platform was successfully added.
		$this->set_results( TRUE, 'The Platform "'.$this->input->post('name').'" has been added.' );
		
		// Insert the Tags information.
		if( !is_array($this->input->post('tag')) )
		{
			$this->stop_transaction();
			return;
		}

		$this->load->model('tag_model');
		
		foreach($this->input->post('tag') as $tag)
		{
			switch( $tag['action'] )
			{
				case 'add':
					$this->tag_model->add_tag( $tag['name'], $this->table, $id );
					if( !$this->has_error('tag') )
					{
						$this->set_results( TRUE, "Tag '".$tag['name']."' successfully added." );
					}
					break;
					
				case 'delete':
					$this->tag_model->delete_tag( $tag['name'], $this->table, $id );
					if( !$this->has_error('tag') )
					{
						$this->set_results( TRUE, "Tag '".$tag['name']."' successfully deleted." );
					}
					break;
			}
		}
		
		// Stop the database transaction.
		$this->stop_transaction();
	}
}

/* End of file platform/admin_add.php */
/* Location: ./application/controllers/platform/admin_add.php */
