<?php

/**
 * Admin_Add
 * Responsible for displaying and process the data entered into the
 * add interface for this table.
 *
 * @package     Database Project
 * @subpackage  controllers
 * @category    news
 * @author      Crystal Barton
 * @version     1.00
 */
class Admin_Add extends MY_Controller
{

	var $table = 'news';
	var $page = 'add';
	var $title = 'News/Reviews >> Add Item';
	var $_item = array();


	/**
	 * Default Constructor.
	 */
	function __construct()
	{ 
		parent::__construct();
		$this->load->model( $this->table.'_model', 'table_model' );
	}


	/**
	 * Display the add interface for the news story.
	 */
	function index()
	{
		if( $this->input->post() )
		{
			// Process the post data.
			$this->_process_post();
			$this->_item = $this->input->post();
		}
		else
		{
			// Get the item's data.
			$this->_item = $this->table_model->get_news_for_admin_add();
		}

		// Get a list of tags.
		if( (!$this->input->post()) || ($this->post_processed_errored()) )
		{
			$this->_item['entries'] = $this->table_model->get_tag_list();
			$this->has_error();
		}
		
		// Store the news story and if there was an error.
		$this->add_content( 'item', $this->_item );
		$this->add_content( 'error', $this->post_processed_errored() );
		
		// Add stylesheets and javascript files.
		$this->add_style( 'util/jquery.selector' );
		$this->add_style( 'util/jquery-ui' );
		$this->add_style( 'admin' );
		$this->add_script( 'util/jquery.selector' );
		$this->add_script( 'util/jquery-ui' );
		$this->add_script( 'news/admin' );
		
		// Show the add item interface.
		$this->show_page( $this->table.'/'.$this->page, $this->title, TRUE );
	}


	/**
	 * Attempts to add the new news story into the database.
	 */
	function _process_post()
	{
		// Start the database transaction.
		$this->start_transaction();
		
		// Check if the item already exists.
		$already_exists = $this->table_model->news_exists(
			$this->input->post('title')
		);
		if( $this->has_error() ) return;
		
		// The news story already exists.
		if( $already_exists )
		{
			$this->set_results( FALSE, 'The News Story "'.$this->input->post('title') . '" already exists.' );
			return;
		}

		// Add the news story.
		$result = $this->table_model->add_news(
			$this->input->post('date'),
		 	$this->input->post('author'),
			$this->input->post('title'),
		 	$this->input->post('synopsis'),
		 	$this->input->post('text'),
			$this->input->post('is_review'),
			$this->input->post('rating')
		);
		if( $this->has_error() ) return;
		
		// Get the news story id auto-generated by the news table.
		$id = $this->table_model->get_news_id(
			$this->input->post('title')
		);
		if( $this->has_error() ) return;
		$this->add_content( 'id', $id );
		
		// The news story was successfully added.
		$this->set_results( TRUE, 'The News Story "'.$this->input->post('title').'" has been added.' );
		
		// Insert the Tags information.
		if( !is_array($this->input->post('newstag')) )
		{
			$this->stop_transaction();
			return;
		}

		$this->load->model('newstag_model');
		
		foreach($this->input->post('newstag') as $tag)
		{
			switch( $tag['action'] )
			{
				case 'add':
					$this->newstag_model->add_tag( $id, $tag['table'], $tag['table-id'] );
					if( !$this->has_error('newstag') )
					{
						$this->set_results( TRUE, "Tag '".$tag['table']." => ".$tag['table-id']."' successfully added." );
					}
					break;
					
				case 'delete':
					$this->newstag_model->delete_tag( $id, $tag['table'], $tag['table-id'] );
					if( !$this->has_error('newstag') )
					{
						$this->set_results( TRUE, "Tag '".$tag['table']." => ".$tag['table-id']."' successfully deleted." );
					}
					break;
			}
		}
		
		// Stop the database transaction.
		$this->stop_transaction();
	}
}

/* End of file news/admin_add.php */
/* Location: ./application/controllers/news/admin_add.php */
